# Generated by Django 4.1.3 on 2022-11-30 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theaters',
            fields=[
                ('theaters_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('seat', models.TextField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
            ],
            options={
                'db_table': 'movies_theaters',
            },
        ),
    ]
